//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public agent()
        {
            this.venues = new HashSet<venue>();
        }
    
        public int agentID { get; set; }
        public string agent_name { get; set; }
        public string agent_email { get; set; }
        public int agent_phone { get; set; }
    
        public virtual ICollection<venue> venues { get; set; }
    }
}
