//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class album
    {
        public int albumsID { get; set; }
        public string images { get; set; }
        public int vendorID { get; set; }
    
        public virtual vendor vendor { get; set; }
    }
}
