//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.bookedvenues = new HashSet<bookedvenue>();
            this.payments = new HashSet<payment>();
            this.reviews = new HashSet<review>();
        }
    
        public int customerID { get; set; }
        public string customer_Fname { get; set; }
        public string customer_Lname { get; set; }
        public string customer_address { get; set; }
        public int customer_phone { get; set; }
        public string customer_username { get; set; }
        public string customer_password { get; set; }
    
        public virtual ICollection<bookedvenue> bookedvenues { get; set; }
        public virtual ICollection<payment> payments { get; set; }
        public virtual ICollection<review> reviews { get; set; }
    }
}
