//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectevent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eventDBEntities : DbContext
    {
        public eventDBEntities()
            : base("name=eventDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<agent> agents { get; set; }
        public virtual DbSet<album> albums { get; set; }
        public virtual DbSet<bookedvenue> bookedvenues { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<FoodItem> FoodItems { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<photography> photographies { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
        public virtual DbSet<venue> venues { get; set; }
    }
}
