//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public int FoodItemsID { get; set; }
        public string Foodtype { get; set; }
        public int Cost { get; set; }
    }
}
