//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class photography
    {
        public photography()
        {
            this.venues = new HashSet<venue>();
        }
    
        public int photographyID { get; set; }
        public string photographer_name { get; set; }
        public int photographer_phone { get; set; }
        public double photographer_cost { get; set; }
    
        public virtual ICollection<venue> venues { get; set; }
    }
}
