//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int reviewID { get; set; }
        public string review_content { get; set; }
        public double review_rating { get; set; }
        public int customerID { get; set; }
        public int venueID { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual venue venue { get; set; }
    }
}
