//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public vendor()
        {
            this.albums = new HashSet<album>();
            this.venues = new HashSet<venue>();
        }
    
        public int vendorID { get; set; }
        public string vendor_Fname { get; set; }
        public string vendor_Lname { get; set; }
        public string vendor_address { get; set; }
        public long vendor_phone { get; set; }
        public string vendor_username { get; set; }
        public string vendor_password { get; set; }
        public string vendor_category { get; set; }
        public bool vendor_status { get; set; }
    
        public virtual ICollection<album> albums { get; set; }
        public virtual ICollection<venue> venues { get; set; }
    }
}
